Automatically switching to curl if wget is not available, like on OS X, BSD, etc.

diff --git a/lib/init b/lib/init
--- a/lib/init
+++ b/lib/init
@@ -54,8 +54,18 @@ if [ ! -d "work/" ]; then
 fi
 
 echo "${banner} downloading all OpenSSL sources - this might take a while"
-wget -r -l2 -nd -Nc -A "*.tar.gz" -A "*.md5" -P "work/" \
-	"https://www.openssl.org/source" &>/dev/null || fail "could not download OpenSSL"
+
+if command -v wget >/dev/null 2>&1 ; then
+	wget -r -l2 -nd -Nc -A "*.tar.gz" -A "*.md5" -P "work/" \
+		"https://www.openssl.org/source" &>/dev/null || fail "could not download OpenSSL"	
+elif command -v curl >/dev/null 2>&1 ; then
+	# Yes, this is ugly
+	cd work && curl -s 'https://www.openssl.org/source/' | grep .tar.gz | sed -e 's/^.*href=\"/https\:\/\/www\.openssl\.org\/source\//g' -e 's/\.tar\.gz.*/\.tar\.gz/g' | uniq | while read url; do curl -LO -# -R -C - "{$url}" -LO -# -R -C - "{$url}.md5" ; done ; cd ..
+else
+	fail "Could't find wget or curl to fetch sources."
+	exit 1
+fi
+
 
 echo "${banner} verifying tarballs:"
 verify_tarballs
